DELETE http://localhost:3001/api/blogs/13
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5vdERlcm1vdEBtYWlsLmNvbSIsImlkIjozLCJpYXQiOjE3MTE2OTg1MTl9.A5dYQYDqPD_EOAYkSYWrSLBQZVztF2zo27U-qsqy8ZA
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlcm1vdCIsImlkIjoyLCJpYXQiOjE3MTE2OTY2NTR9.TcUIU2eMBxVewwVPrQ6awgYrz1synr3OM39VDj7KqFc