POST http://localhost:3001/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlcm1vdEBuZXdlbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNzExODc0MjY3fQ.IQhgD5miYgsTkJl2z-K_oYdb5wlZtlUpALcZNB3tSaw
Content-Type: application/json

{
  "title": "First class tests",
  "author": "Robert C. Martin",
  "url": "https://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.html",
  "year": "1989"
}

###

POST http://localhost:3001/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlcm1vdCIsImlkIjoyLCJpYXQiOjE3MTE2OTY2NTR9.TcUIU2eMBxVewwVPrQ6awgYrz1synr3OM39VDj7KqFc
Content-Type: application/json

{
  "title": "React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/"
}

###

POST http://localhost:3001/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlcm1vdCIsImlkIjoyLCJpYXQiOjE3MTE2OTY2NTR9.TcUIU2eMBxVewwVPrQ6awgYrz1synr3OM39VDj7KqFc
Content-Type: application/json

{
  "title": "Go To Statement Considered Harmful",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html"
    
}

###

POST http://localhost:3001/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlcm1vdCIsImlkIjoyLCJpYXQiOjE3MTE2OTY2NTR9.TcUIU2eMBxVewwVPrQ6awgYrz1synr3OM39VDj7KqFc
Content-Type: application/json

{
  "title": "Canonical string reduction",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html"
    
}

###

POST http://localhost:3001/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlcm1vdCIsImlkIjoyLCJpYXQiOjE3MTE2OTY2NTR9.TcUIU2eMBxVewwVPrQ6awgYrz1synr3OM39VDj7KqFc
Content-Type: application/json

{
  "title": "TDD harms architecture",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html"
    
}

###

POST http://localhost:3001/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlcm1vdCIsImlkIjoyLCJpYXQiOjE3MTE2OTY2NTR9.TcUIU2eMBxVewwVPrQ6awgYrz1synr3OM39VDj7KqFc
Content-Type: application/json

{
  "title": "Type wars",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html"
    
}