POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "dermot@neweremail.com",
  "password": "secret",
  "name": "notDermy notDermerson"
}

###

PUT http://localhost:3001/api/users/notDermot@mail.com
Content-Type: application/json

{
  "username": "dermot@newemail.com"
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "dermot@neweremail.com",
  "password": "secret"
}
